language: ruby
rvm:
- 2.2
deploy:
  provider: heroku
  api_key:
    secure: iNHFEDQT6m3OZVKzrdUrjcp/1o5g0l0Cbzsb0BB7pPH36PHBAb8TN5yIFyu3SnthuXp3QhLS5BBK22pjoS0T+yRRVw7AosVCyrKOeqteVEzqD1yhwzwyDWb2HIseW2ofSsCBz52krn38xmiuu3seNujb9LkdOGvutASPm+uB/sRODcFezD8I4aJU8wRiQOSHqJxDStENC8WkR5nIg/3qFuiIAc09E15thNN5wRNY2JI7Y01X3x7w57tSDyh+8m9GuQLmyVQrPPoHCGWj2YbjiZ7GkqfgfOMV8K611Vn38u79fOTvXvWe7eLbLbVhuftDNL1qKq2j0oqA+dueWhvP7Wo5rU0vZvCg0W3/ravFelbY9+Azs0bcL2KGkRXJtgQfzoRV0yCp/ltQw5xNJBKIFEVCCszkAzVSzYhjKb0P6ieD8Lz0kEkrPX6BKoaX0p5Ck9rdf955BG1EpYfZS9DuDw+pN8zdJ29dCO3bFttdiBD+9YN9vtq+5hE5QKLa3eAqd9pmDovB8YJJubreOhLVnLnVUnmcCdSceILZiMLxK2m7ytY6znD4j2rUigBtPb1urhjW20O+UAm3QhNMoJXSRyQEZUpzU0RAQx9HLkv2bPcUGIhgEYr/ZU8BlbS8d9Eb4G9ldeUOCWkZVCcMNSTQ+HcJ9VADZeCyV50Xx9iB7jc=
  app: lpa2-francois
  on:
    repo: FrancoisGETE/projet
