# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 261651027bf357b9586da62086a7c7d6bab2845e30fd60bd0cb516668da14f8309f439acca24befd7f0b996ed9dce083c403f0aef09fd1d62bc46536e0323397

test:
  secret_key_base: b2b9783434eb0f4277fa85d755a7126d0e008d54573719ccab9d4046cbdf2a419d1c5e85113767d701a601509c1106acfe8f2dd046905349c843b58735d0c439

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
